export enum AiToolType {
    BING = 'BING',
    AMAZON = 'AMAZON',
    TAVILY = 'TAVILY',
    GOOGLE = 'GOOGLE',
    YOU_TUBE = 'YOU_TUBE',
    WIKIPEDIA = 'WIKIPEDIA',
    GOOGLE_NEWS = 'GOOGLE_NEWS',
    WOLFRAM_ALPHA = 'WOLFRAM_ALPHA',
}