export enum AiToolType {
    TEST = 'TEST',
    // BING = 'BING',
    // AMAZON = 'AMAZON',
    // YOU_TUBE = 'YOU_TUBE',
    // GOOGLE_NEWS = 'GOOGLE_NEWS',
    //
    TAVILY = 'TAVILY',
    GOOGLE = 'GOOGLE',
    YANDEX = 'YANDEX',
    WIKIPEDIA = 'WIKIPEDIA',
    WOLFRAM_ALPHA = 'WOLFRAM_ALPHA',
    IMAGE_RECOGNITION = 'IMAGE_RECOGNITION',
    IMAGE_DRAWING_DALLE_2 = 'IMAGE_DRAWING_DALLE_2',
    IMAGE_DRAWING_DALLE_3 = 'IMAGE_DRAWING_DALLE_3',
    CONTENT_SUMMARIZATION = 'CONTENT_SUMMARIZATION',

    DOCUMENT_GENIUSES = 'DOCUMENT_GENIUSES',
}

export interface IAiToolConsumption {
    type: AiToolType;
    value: string;
}