export enum AiToolType {
    TEST = 'TEST',

    TNVED = 'TNVED',
    COMMON = 'COMMON',
    OCCULTIST = 'OCCULTIST',

    TAVILY = 'TAVILY',
    GOOGLE = 'GOOGLE',
    YANDEX = 'YANDEX',
    WIKIPEDIA = 'WIKIPEDIA',
    WOLFRAM_ALPHA = 'WOLFRAM_ALPHA',
    IMAGE_RECOGNITION = 'IMAGE_RECOGNITION',
    IMAGE_DRAWING_DALLE_2 = 'IMAGE_DRAWING_DALLE_2',
    IMAGE_DRAWING_DALLE_3 = 'IMAGE_DRAWING_DALLE_3',
    CONTENT_SUMMARIZATION = 'CONTENT_SUMMARIZATION',
}

export interface IAiToolConsumption {
    type: string;
    value: string;
}