export enum LoginResource {
    VK_INTERNAL = 'VK_INTERNAL',
    TELEGRAM_INTERNAL = 'TELEGRAM_INTERNAL',

    VK = 'VK',
    MAIL = 'MAIL',
    YANDEX = 'YANDEX',
    GOOGLE = 'GOOGLE',
    ETHEREUM = 'ETHEREUM',
    TELEGRAM = 'TELEGRAM',
}